[package]
name = "icssc-discord-bot"
version = "1.0.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
anyhow = "1.0.91"
chrono = "0.4.38"
clap = { version = "4.5.23", features = ["cargo"] }
discord-md = "3.0.0"
dotenv = "0.15.0"
itertools = "0.14.0"
petgraph = "0.7.1"
pluralizer = "0.5.0"
poise = "0.6.1"
rand = "0.9.0"
rand_chacha = "0.9.0"
regex = "1.11.0"
sea-orm = { version = "1.1.0", features = ["sqlx-postgres", "runtime-tokio", "macros", "with-chrono"] }
serenity = { version = "0.12.4", features = ["full"] }
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
entity = { path = "entity" }
migration = { path = "migration" }
serde = "1.0.226"
jsonwebtoken = "9.3.1"
reqwest = { version = "0.12.23", features = ["json"] }

[profile.release]
lto = "fat"
