[package]
name = "ics-spottings-council"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["cargo"] }
poise = "0.6.1"
serenity = "0.12.4"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
discord-md = "3.0.0"
dotenv = "0.15.0"
pluralizer = "0.5.0"
itertools = "0.14.0"
rand = "0.9.0"
