[package]
name = "icssc-discord-bot"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.91"
chrono = "0.4.38"
clap = { version = "4.5.23", features = ["cargo"] }
diesel = { version = "2.2.7", features = ["postgres", "chrono"] }
diesel-async = { version = "0.5.2", features = ["postgres", "deadpool"] }
discord-md = "3.0.0"
dotenv = "0.15.0"
itertools = "0.14.0"
petgraph = "0.7.1"
pluralizer = "0.5.0"
poise = "0.6.1"
rand = "0.9.0"
rand_chacha = "0.3.1"
regex = "1.11.0"
serenity = { version = "0.12.4", features = ["full"] }
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
