[workspace]
members = [".", "entity", "migration"]

[package]
name = "ics-spottings-council"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["cargo"] }
poise = "0.6.1"
serenity = { version = "0.12.4", features = ["full"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
discord-md = "3.0.0"
dotenv = "0.15.0"
pluralizer = "0.5.0"
itertools = "0.14.0"
rand = "0.9.0"
sea-orm = { version = "1.1.0", features = ["sqlx-postgres", "runtime-tokio", "macros", "with-chrono"] }
entity = { path = "entity" }
migration = { path = "migration" }

[profile.release]
lto = "fat"
